image: gitpod/workspace-go:latest
tasks:
  - name: install staticheck
    command: go install honnef.co/go/tools/cmd/staticcheck@latest
vscode:
  extensions:
    - golang.go
    - dracula-theme.theme-dracula
