image: gitpod/workspace-go:2022-08-04-03-33-59

tasks:
  - name: install staticheck
    init: go install honnef.co/go/tools/cmd/staticcheck@latest
  - name: install go-task
    init: go install github.com/go-task/task/v3/cmd/task@latest
vscode:
  extensions:
    - golang.go
