version: "3"

vars:
  APP_NAME: app

includes:
  OS: 
    taskfile: ./Taskfile_{{OS}}.yml
    internal: true

tasks:
  default:
    cmds:
      - task: run
  init:
    cmds:
      - go mod init {{.APP_NAME}}
      - go get -u github.com/devlights/gomy@latest
      - echo -e "package main\nfunc main(){\n}" > main.go
      - task: fmt
      - task: build
  fmt:
    cmds:
      - goimports -w .
  vet:
    cmds:
      - go vet ./...
      - staticcheck ./...
  lint:
    cmds:
      - revive -formatter stylish ./...
  build:
    cmds:
      - go mod tidy
      - go build -o {{.APP_NAME}}{{exeExt}} *.go
    sources:
      - ./*.go
    generates:
      - ./{{.APP_NAME}}{{exeExt}}
    method: timestamp
  run:
    deps: [ build ]
    cmds:
      - time ./{{.APP_NAME}}{{exeExt}} {{.CLI_ARGS}}
  version:
    cmds:
      - go version
  clean:
    cmds:
      - task: OS:clean
