version: "3"

tasks:
  default:
    cmds:
      - task: run
  init:
    cmds:
      - go mod init app
      - go get -u github.com/devlights/gomy@latest
      - echo -e "package main\nfunc main(){\n}" > main.go
      - task: fmt
      - task: run
  fmt:
    cmds:
      - goimports -w .
  vet:
    cmds:
      - go vet ./...
      - staticcheck ./...
  lint:
    cmds:
      - revive -formatter stylish ./...
  build:
    cmds:
      - go mod tidy
      - go build -o app main.go
    sources:
      - ./*.go
    generates:
      - app{{exeExt}}
    method: timestamp
  run:
    deps: [ build ]
    cmds:
      - ./app
  version:
    cmds:
      - go version
  clean:
    cmds:
      - go clean
      - rm go.* *.go
      - rm -rf ./.task
