version: '3'

tasks:
  init:
    cmds:
      - go mod init app
      - go get -u github.com/devlights/gomy@latest
      - gp open main.go
  run:
    cmds:
      - go run main.go
  version:
    cmds:
      - go version
  clean:
    cmds:
      - rm go.* *.go
