version: '3'

tasks:
  init:
    cmds:
      - go mod init app
      - gp open main.go
  run:
    cmds:
      - go run main.go
  version:
    cmds:
      - go version
  clean:
    cmds:
      - rm go.mod *.go
